name: HITS
on:
    push:
    workflow_dispatch:
    schedule:
      - cron: '*/5 * * * *'
      # - cron: '*/31 * * * *'
    # schedule:
    #     - cron: '1/2 * * * *'
    # schedule:
    #     - cron: '0 0 0/24 * * *'
        


env:

    NODEPAY_TOKEN: ${{ secrets.NODEPAY_TOKEN }}

jobs:  
    # job:
    #   runs-on: ubuntu-latest
    #   timeout-minutes: 1440
    #   steps:
    #     - name: Checkout Code
    #       uses: actions/checkout@v4
    #     - name: Check for dockerenv file1
    #       run: |
    #         docker run -d --name socks5_4444 -p 4444:1080 -e PROXY_USER=user -e PROXY_PASSWORD=password olebedev/socks5 
    #         docker run --name 3proxy -d -p 3128:3128 --env PROXY_LOGIN=user --env PROXY_PASSWORD=password riftbit/3proxy
    #     - name: Nodepay-install
    #       run: |
    #         docker ps
    #         cd nodepay
    #         python -m venv venv
    #         source venv/bin/activate
    #         pip install -r requirements.txt
    #     - name: Nodepay-run
    #       run: |
    #         cd nodepay
    #         source venv/bin/activate
    #         python noproxy.py

    job_9hits:
        runs-on: ubuntu-latest
        timeout-minutes: 4.5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            # - name: download
            #   run: |
            #     DIR=$(pwd)
            #     wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
            #     tar -xvf 9hitsv3-linux64.tar.bz2
            #     cd 9hitsv3-linux64
            #     HITS_DIR=$(pwd)
            #     cp -rf $DIR/hits/config $HITS_DIR
            # - name: update x
            #   run: |
            #     sudo apt-get update
            #     sudo apt-get install -y xvfb
            #     sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
            #     sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
            #     sudo apt-get -y install imagemagick x11-apps 
            - name: Dawn-install
              run: |
                cd dawn_asinx
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            # - name: Dawn-run
            #   run: |
            #     cd dawn_asinx
            #     source venv/bin/activate
            #     nohup python main.py &
            - name: Dawn-run
              run: |
                cd dawn_asinx
                source venv/bin/activate
                python main.py 
            # - name: run Hits
            #   run: |
            #       Xvfb -ac :99 -screen 0 1280x1024x16 &
            #       export DISPLAY=:99

            #       cd 9hitsv3-linux64
            #       ./9hits 
              

      # job_9hits1:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

                

    #         - name: run
    #           run: |
    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99

    #             cd 9hitsv3-linux64
    #             ./9hits
    # job_9hits2:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

                

              
    #         - name: run
    #           run: |
    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99
              
    #             cd 9hitsv3-linux64
    #             ./9hits
    # job_9hits3:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99

    #         - name: run
    #           run: |
              
    #             cd 9hitsv3-linux64
    #             ./9hits
    # job_9hits4:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99

    #         - name: run
    #           run: |
              
    #             cd 9hitsv3-linux64
    #             ./9hits

    # job_nodepay1:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Nodepay-install
    #           run: |
    #             cd nodepay
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Nodepay-run
    #           run: |
    #             cd nodepay
    #             source venv/bin/activate
    #             timeout 2m python noproxy.py
    #           shell: bash
    # job_nodepay:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Nodepay-install
    #           run: |
    #             cd nodepay
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Nodepay-run
    #           run: |
    #             cd nodepay
    #             source venv/bin/activate
    #             timeout 2m python noproxy.py
    #           shell: bash                
    # job_grass:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Grass-install
    #           run: |
    #             cd grass
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Grass-run
    #           run: |
    #             cd grass
    #             source venv/bin/activate
    #             python grass.py