name: NODEPAY
on:
    # push:
    workflow_dispatch:
    # schedule:
    # #   - cron: '*/15 * * * *'
    #   - cron: '0 * * * *'
    # schedule:
    #     - cron: '1/2 * * * *'
    # schedule:
    #     - cron: '0 0 0/24 * * *'
        

env:

    NODEPAY_TOKEN: ${{ secrets.NODEPAY_TOKEN }}

# 1440

jobs:  
    job_nodepay2:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Nodepay-install
              run: |
                cd nodepay
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Nodepay-run
              run: |
                cd nodepay
                source venv/bin/activate
                python noproxy.py
    job_nodepay1:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Nodepay-install
              run: |
                cd nodepay
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Nodepay-run
              run: |
                cd nodepay
                source venv/bin/activate
                python noproxy.py
    job_nodepay:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Nodepay-install
              run: |
                cd nodepay
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Nodepay-run
              run: |
                cd nodepay
                source venv/bin/activate
                python noproxy.py


    # job_grass:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Grass-install
    #           run: |
    #             cd grass
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Grass-run
    #           run: |
    #             cd grass
    #             source venv/bin/activate
    #             python grass.py